name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  check-and-close:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        if: ${{ github.event.repository.fork == false }}
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "This pull request has been automatically closed because it was opened in the upstream repository. Create your PRs within your own forked repository."

